/* js/data.js — 牌面映射表（78 张，Rider-Waite-Smith 体系）
 * 全局变量，不用 import。id 为稳定标识，file 为 cards/ 下的中文文件名。 */
var TAROT_BACK_IMAGE = "cards/back.jpg";

var TAROT_CARDS = [
  { id: "major-00", file: "0愚人.jpg", name: "愚人", en: "The Fool", suit: "major", suitCn: "大阿卡纳", num: 0, arcana: "major" },
  { id: "major-01", file: "1魔术师.jpg", name: "魔术师", en: "The Magician", suit: "major", suitCn: "大阿卡纳", num: 1, arcana: "major" },
  { id: "major-02", file: "2女祭司.jpg", name: "女祭司", en: "The High Priestess", suit: "major", suitCn: "大阿卡纳", num: 2, arcana: "major" },
  { id: "major-03", file: "3女皇.jpg", name: "女皇", en: "The Empress", suit: "major", suitCn: "大阿卡纳", num: 3, arcana: "major" },
  { id: "major-04", file: "4皇帝.jpg", name: "皇帝", en: "The Emperor", suit: "major", suitCn: "大阿卡纳", num: 4, arcana: "major" },
  { id: "major-05", file: "5教皇.jpg", name: "教皇", en: "The Hierophant", suit: "major", suitCn: "大阿卡纳", num: 5, arcana: "major" },
  { id: "major-06", file: "6恋人.jpg", name: "恋人", en: "The Lovers", suit: "major", suitCn: "大阿卡纳", num: 6, arcana: "major" },
  { id: "major-07", file: "7战车.jpg", name: "战车", en: "The Chariot", suit: "major", suitCn: "大阿卡纳", num: 7, arcana: "major" },
  { id: "major-08", file: "8力量.jpg", name: "力量", en: "Strength", suit: "major", suitCn: "大阿卡纳", num: 8, arcana: "major" },
  { id: "major-09", file: "9隐者.jpg", name: "隐者", en: "The Hermit", suit: "major", suitCn: "大阿卡纳", num: 9, arcana: "major" },
  { id: "major-10", file: "10命运之轮.jpg", name: "命运之轮", en: "Wheel of Fortune", suit: "major", suitCn: "大阿卡纳", num: 10, arcana: "major" },
  { id: "major-11", file: "11正义.jpg", name: "正义", en: "Justice", suit: "major", suitCn: "大阿卡纳", num: 11, arcana: "major" },
  { id: "major-12", file: "12吊人.jpg", name: "吊人", en: "The Hanged Man", suit: "major", suitCn: "大阿卡纳", num: 12, arcana: "major" },
  { id: "major-13", file: "13死神.jpg", name: "死神", en: "Death", suit: "major", suitCn: "大阿卡纳", num: 13, arcana: "major" },
  { id: "major-14", file: "14节制.jpg", name: "节制", en: "Temperance", suit: "major", suitCn: "大阿卡纳", num: 14, arcana: "major" },
  { id: "major-15", file: "15恶魔.jpg", name: "恶魔", en: "The Devil", suit: "major", suitCn: "大阿卡纳", num: 15, arcana: "major" },
  { id: "major-16", file: "16高塔.jpg", name: "高塔", en: "The Tower", suit: "major", suitCn: "大阿卡纳", num: 16, arcana: "major" },
  { id: "major-17", file: "17星星.jpg", name: "星星", en: "The Star", suit: "major", suitCn: "大阿卡纳", num: 17, arcana: "major" },
  { id: "major-18", file: "18月亮.jpg", name: "月亮", en: "The Moon", suit: "major", suitCn: "大阿卡纳", num: 18, arcana: "major" },
  { id: "major-19", file: "19太阳.jpg", name: "太阳", en: "The Sun", suit: "major", suitCn: "大阿卡纳", num: 19, arcana: "major" },
  { id: "major-20", file: "20审判.jpg", name: "审判", en: "Judgement", suit: "major", suitCn: "大阿卡纳", num: 20, arcana: "major" },
  { id: "major-21", file: "21世界.jpg", name: "世界", en: "The World", suit: "major", suitCn: "大阿卡纳", num: 21, arcana: "major" },
  { id: "cups-1", file: "圣杯1.jpg", name: "圣杯1", en: "Cups 1", suit: "cups", suitCn: "圣杯", num: 1, arcana: "minor" },
  { id: "cups-2", file: "圣杯2.jpg", name: "圣杯2", en: "Cups 2", suit: "cups", suitCn: "圣杯", num: 2, arcana: "minor" },
  { id: "cups-3", file: "圣杯3.jpg", name: "圣杯3", en: "Cups 3", suit: "cups", suitCn: "圣杯", num: 3, arcana: "minor" },
  { id: "cups-4", file: "圣杯4.jpg", name: "圣杯4", en: "Cups 4", suit: "cups", suitCn: "圣杯", num: 4, arcana: "minor" },
  { id: "cups-5", file: "圣杯5.jpg", name: "圣杯5", en: "Cups 5", suit: "cups", suitCn: "圣杯", num: 5, arcana: "minor" },
  { id: "cups-6", file: "圣杯6.jpg", name: "圣杯6", en: "Cups 6", suit: "cups", suitCn: "圣杯", num: 6, arcana: "minor" },
  { id: "cups-7", file: "圣杯7.jpg", name: "圣杯7", en: "Cups 7", suit: "cups", suitCn: "圣杯", num: 7, arcana: "minor" },
  { id: "cups-8", file: "圣杯8.jpg", name: "圣杯8", en: "Cups 8", suit: "cups", suitCn: "圣杯", num: 8, arcana: "minor" },
  { id: "cups-9", file: "圣杯9.jpg", name: "圣杯9", en: "Cups 9", suit: "cups", suitCn: "圣杯", num: 9, arcana: "minor" },
  { id: "cups-10", file: "圣杯10.jpg", name: "圣杯10", en: "Cups 10", suit: "cups", suitCn: "圣杯", num: 10, arcana: "minor" },
  { id: "cups-page", file: "圣杯侍从.jpg", name: "圣杯侍从", en: "Cups Page", suit: "cups", suitCn: "圣杯", num: 0, arcana: "minor" },
  { id: "cups-knight", file: "圣杯骑士.jpg", name: "圣杯骑士", en: "Cups Knight", suit: "cups", suitCn: "圣杯", num: 0, arcana: "minor" },
  { id: "cups-queen", file: "圣杯王后.jpg", name: "圣杯王后", en: "Cups Queen", suit: "cups", suitCn: "圣杯", num: 0, arcana: "minor" },
  { id: "cups-king", file: "圣杯国王.jpg", name: "圣杯国王", en: "Cups King", suit: "cups", suitCn: "圣杯", num: 0, arcana: "minor" },
  { id: "swords-1", file: "宝剑1.jpg", name: "宝剑1", en: "Swords 1", suit: "swords", suitCn: "宝剑", num: 1, arcana: "minor" },
  { id: "swords-2", file: "宝剑2.jpg", name: "宝剑2", en: "Swords 2", suit: "swords", suitCn: "宝剑", num: 2, arcana: "minor" },
  { id: "swords-3", file: "宝剑3.jpg", name: "宝剑3", en: "Swords 3", suit: "swords", suitCn: "宝剑", num: 3, arcana: "minor" },
  { id: "swords-4", file: "宝剑4.jpg", name: "宝剑4", en: "Swords 4", suit: "swords", suitCn: "宝剑", num: 4, arcana: "minor" },
  { id: "swords-5", file: "宝剑5.jpg", name: "宝剑5", en: "Swords 5", suit: "swords", suitCn: "宝剑", num: 5, arcana: "minor" },
  { id: "swords-6", file: "宝剑6.jpg", name: "宝剑6", en: "Swords 6", suit: "swords", suitCn: "宝剑", num: 6, arcana: "minor" },
  { id: "swords-7", file: "宝剑7.jpg", name: "宝剑7", en: "Swords 7", suit: "swords", suitCn: "宝剑", num: 7, arcana: "minor" },
  { id: "swords-8", file: "宝剑8.jpg", name: "宝剑8", en: "Swords 8", suit: "swords", suitCn: "宝剑", num: 8, arcana: "minor" },
  { id: "swords-9", file: "宝剑9.jpg", name: "宝剑9", en: "Swords 9", suit: "swords", suitCn: "宝剑", num: 9, arcana: "minor" },
  { id: "swords-10", file: "宝剑10.jpg", name: "宝剑10", en: "Swords 10", suit: "swords", suitCn: "宝剑", num: 10, arcana: "minor" },
  { id: "swords-page", file: "宝剑侍从.jpg", name: "宝剑侍从", en: "Swords Page", suit: "swords", suitCn: "宝剑", num: 0, arcana: "minor" },
  { id: "swords-knight", file: "宝剑骑士.jpg", name: "宝剑骑士", en: "Swords Knight", suit: "swords", suitCn: "宝剑", num: 0, arcana: "minor" },
  { id: "swords-queen", file: "宝剑王后.jpg", name: "宝剑王后", en: "Swords Queen", suit: "swords", suitCn: "宝剑", num: 0, arcana: "minor" },
  { id: "swords-king", file: "宝剑国王.jpg", name: "宝剑国王", en: "Swords King", suit: "swords", suitCn: "宝剑", num: 0, arcana: "minor" },
  { id: "pentacles-1", file: "星币1.jpg", name: "星币1", en: "Pentacles 1", suit: "pentacles", suitCn: "星币", num: 1, arcana: "minor" },
  { id: "pentacles-2", file: "星币2.jpg", name: "星币2", en: "Pentacles 2", suit: "pentacles", suitCn: "星币", num: 2, arcana: "minor" },
  { id: "pentacles-3", file: "星币3.jpg", name: "星币3", en: "Pentacles 3", suit: "pentacles", suitCn: "星币", num: 3, arcana: "minor" },
  { id: "pentacles-4", file: "星币4.jpg", name: "星币4", en: "Pentacles 4", suit: "pentacles", suitCn: "星币", num: 4, arcana: "minor" },
  { id: "pentacles-5", file: "星币5.jpg", name: "星币5", en: "Pentacles 5", suit: "pentacles", suitCn: "星币", num: 5, arcana: "minor" },
  { id: "pentacles-6", file: "星币6.jpg", name: "星币6", en: "Pentacles 6", suit: "pentacles", suitCn: "星币", num: 6, arcana: "minor" },
  { id: "pentacles-7", file: "星币7.jpg", name: "星币7", en: "Pentacles 7", suit: "pentacles", suitCn: "星币", num: 7, arcana: "minor" },
  { id: "pentacles-8", file: "星币8.jpg", name: "星币8", en: "Pentacles 8", suit: "pentacles", suitCn: "星币", num: 8, arcana: "minor" },
  { id: "pentacles-9", file: "星币9.jpg", name: "星币9", en: "Pentacles 9", suit: "pentacles", suitCn: "星币", num: 9, arcana: "minor" },
  { id: "pentacles-10", file: "星币10.jpg", name: "星币10", en: "Pentacles 10", suit: "pentacles", suitCn: "星币", num: 10, arcana: "minor" },
  { id: "pentacles-page", file: "星币侍从.jpg", name: "星币侍从", en: "Pentacles Page", suit: "pentacles", suitCn: "星币", num: 0, arcana: "minor" },
  { id: "pentacles-knight", file: "星币骑士.jpg", name: "星币骑士", en: "Pentacles Knight", suit: "pentacles", suitCn: "星币", num: 0, arcana: "minor" },
  { id: "pentacles-queen", file: "星币王后.jpg", name: "星币王后", en: "Pentacles Queen", suit: "pentacles", suitCn: "星币", num: 0, arcana: "minor" },
  { id: "pentacles-king", file: "星币国王.jpg", name: "星币国王", en: "Pentacles King", suit: "pentacles", suitCn: "星币", num: 0, arcana: "minor" },
  { id: "wands-1", file: "权杖1.jpg", name: "权杖1", en: "Wands 1", suit: "wands", suitCn: "权杖", num: 1, arcana: "minor" },
  { id: "wands-2", file: "权杖2.jpg", name: "权杖2", en: "Wands 2", suit: "wands", suitCn: "权杖", num: 2, arcana: "minor" },
  { id: "wands-3", file: "权杖3.jpg", name: "权杖3", en: "Wands 3", suit: "wands", suitCn: "权杖", num: 3, arcana: "minor" },
  { id: "wands-4", file: "权杖4.jpg", name: "权杖4", en: "Wands 4", suit: "wands", suitCn: "权杖", num: 4, arcana: "minor" },
  { id: "wands-5", file: "权杖5.jpg", name: "权杖5", en: "Wands 5", suit: "wands", suitCn: "权杖", num: 5, arcana: "minor" },
  { id: "wands-6", file: "权杖6.jpg", name: "权杖6", en: "Wands 6", suit: "wands", suitCn: "权杖", num: 6, arcana: "minor" },
  { id: "wands-7", file: "权杖7.jpg", name: "权杖7", en: "Wands 7", suit: "wands", suitCn: "权杖", num: 7, arcana: "minor" },
  { id: "wands-8", file: "权杖8.jpg", name: "权杖8", en: "Wands 8", suit: "wands", suitCn: "权杖", num: 8, arcana: "minor" },
  { id: "wands-9", file: "权杖9.jpg", name: "权杖9", en: "Wands 9", suit: "wands", suitCn: "权杖", num: 9, arcana: "minor" },
  { id: "wands-10", file: "权杖10.jpg", name: "权杖10", en: "Wands 10", suit: "wands", suitCn: "权杖", num: 10, arcana: "minor" },
  { id: "wands-page", file: "权杖侍从.jpg", name: "权杖侍从", en: "Wands Page", suit: "wands", suitCn: "权杖", num: 0, arcana: "minor" },
  { id: "wands-knight", file: "权杖骑士.jpg", name: "权杖骑士", en: "Wands Knight", suit: "wands", suitCn: "权杖", num: 0, arcana: "minor" },
  { id: "wands-queen", file: "权杖王后.jpg", name: "权杖王后", en: "Wands Queen", suit: "wands", suitCn: "权杖", num: 0, arcana: "minor" },
  { id: "wands-king", file: "权杖国王.jpg", name: "权杖国王", en: "Wands King", suit: "wands", suitCn: "权杖", num: 0, arcana: "minor" },
];

/* id -> 卡片对象 的索引 */
var TAROT_BY_ID = (function () {
  var m = {};
  for (var i = 0; i < TAROT_CARDS.length; i++) m[TAROT_CARDS[i].id] = TAROT_CARDS[i];
  return m;
})();
